ProgrammersBlog.Mvc/Areas/Admin/Controllers/ArticlesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using ProgrammersBlog.Entities.ComplexTypes;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Mvc.Helpers.Abstracts;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Results.Abstract;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using System.Text.Json;
using System.Text.Json.Serialization;


namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers;

[Area("Admin")]
public class ArticlesController : BaseController
{
    private readonly IArticleService _articleService;
    private readonly ICategoryService _categoryService;
    private readonly IToastNotification _toastNotification;

    public ArticlesController(IArticleService articleService, ICategoryService categoryService, UserManager<User> userManager, IMapper mapper, IImageHelper imageHelper, IToastNotification toastNotification) : base(userManager, mapper, imageHelper)
    {
        _articleService = articleService;
        _categoryService = categoryService;
        _toastNotification = toastNotification;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        IDataResult<ArticleListDto> result = await _articleService.GetAllByNonDeletedAsync();
        if (result.ResultStatus == ResultStatus.Success)
            return View(result.Data);
        return NotFound();
    }

    [HttpGet]
    public async Task<IActionResult> Add()
    {
        IDataResult<CategoryListDto> result = await _categoryService.GetAllByNonDeletedAndActiveAsync();
        if(result.ResultStatus == ResultStatus.Success)
        {
            return View(new ArticleAddViewModel
            {
                Categories = result.Data.Categories
        });
        }
        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> Add(ArticleAddViewModel articleAddViewModel)
    {
        if (ModelState.IsValid)
        {
            ArticleAddDto articleAddDto = Mapper.Map<ArticleAddDto>(articleAddViewModel);
            IDataResult<ImageUploadedDto> imageResult = await ImageHelper.UploadAsync(articleAddViewModel.Title, articleAddViewModel.ThumbnailFile, PictureType.Post);
            articleAddDto.Thumbnail = imageResult.Data.FullName;
            var result = await _articleService.AddAsync(articleAddDto, LoggedInUser.UserName, LoggedInUser.Id);
            if(result.ResultStatus == ResultStatus.Success)
            {
                _toastNotification.AddSuccessToastMessage(result.Message, new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", result.Message);
            }
        }
        IDataResult<CategoryListDto> categories = await _categoryService.GetAllByNonDeletedAndActiveAsync();
        articleAddViewModel.Categories = categories.Data.Categories;
        return View(articleAddViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int articleId)
    {
        IDataResult<ArticleUpdateDto> articleResult = await _articleService.GetArticleUpdateDtoAsync(articleId);
        IDataResult<CategoryListDto> categoriesResult = await _categoryService.GetAllByNonDeletedAndActiveAsync();
        if(articleResult.ResultStatus == ResultStatus.Success && categoriesResult.ResultStatus == ResultStatus.Success)
        {
            ArticleUpdateViewModel articleUpdateViewModel = Mapper.Map<ArticleUpdateViewModel>(articleResult.Data);
            articleUpdateViewModel.Categories = categoriesResult.Data.Categories;
            return View(articleUpdateViewModel);
        }
        else
        {
            return NotFound();
        }
    }

    [HttpPost]
    public async Task<IActionResult> Update(ArticleUpdateViewModel articleUpdateViewModel)
    {
        if (ModelState.IsValid)
        {
            bool isNewThumbnailUploaded = false;
            string oldThumbnail = articleUpdateViewModel.Thumbnail;
            if(articleUpdateViewModel.ThumbnailFile is not null)
            {
                IDataResult<ImageUploadedDto> uploadedImageResult = await ImageHelper.UploadAsync(articleUpdateViewModel.Title, articleUpdateViewModel.ThumbnailFile, PictureType.Post);
                articleUpdateViewModel.Thumbnail = uploadedImageResult.ResultStatus == ResultStatus.Success
                    ? uploadedImageResult.Data.FullName
                    : "postImages/defaultThumbnail.jpg";
                if(oldThumbnail != "postImages/defaultThumbnail.jpg")
                {
                    isNewThumbnailUploaded = true;
                }
            }
            ArticleUpdateDto articleUpdateDto = Mapper.Map<ArticleUpdateDto>(articleUpdateViewModel);
            var result = await _articleService.UpdateAsync(articleUpdateDto, LoggedInUser.UserName);
            if (result.ResultStatus == ResultStatus.Success)
            {
                if (isNewThumbnailUploaded)
                {
                    ImageHelper.Delete(oldThumbnail);
                }
                _toastNotification.AddSuccessToastMessage(result.Message, new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", result.Message);
            }
        }
        IDataResult<CategoryListDto> categories = await _categoryService.GetAllByNonDeletedAndActiveAsync();
        articleUpdateViewModel.Categories = categories.Data.Categories;
        return View(articleUpdateViewModel);
    }

    [HttpPost]
    public async Task<JsonResult> Delete(int articleId)
    {
        var result = await _articleService.DeleteAsync(articleId, LoggedInUser.UserName);
        string articleResult = JsonSerializer.Serialize(result);
        return Json(articleResult);
    }

    [HttpGet]
    public async Task<JsonResult> GetAllArticles()
    {
        var articles = await _articleService.GetAllByNonDeletedAndActiveAsync();
        string articleResult = JsonSerializer.Serialize(articles, new JsonSerializerOptions
        {
            ReferenceHandler = ReferenceHandler.Preserve
        });
        return Json(articleResult);
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Mvc.Helpers.Abstracts;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using ProgrammersBlog.Shared.Utilities.Results.Concrete;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin,Editor")]
public class CategoriesController : BaseController
{
    private readonly ICategoryService _categoryService;

    public CategoriesController(ICategoryService categoryService,UserManager<User> userManager, IMapper mapper, IImageHelper imageHelper) : base(userManager,mapper,imageHelper)
    {
        _categoryService = categoryService;
    }

    public async Task<IActionResult> Index()
    {
        var result = await _categoryService.GetAllByNonDeletedAsync();
        return View(result.Data);
    }

    [HttpGet]
    public IActionResult Add()
    {
        return PartialView("_CategoryAddPartial");
    }

    [HttpPost]
    public async Task<IActionResult> Add(CategoryAddDto categoryAddDto)
    {
        if (ModelState.IsValid)
        {
            var result = await _categoryService.AddAsync(categoryAddDto, LoggedInUser.UserName);
            if(result.ResultStatus is ResultStatus.Success)
            {
                var categoryAddAjaxModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
                {
                    CategoryDto = result.Data,
                    CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
                });
                return Json(categoryAddAjaxModel);
            }
        }
        var categoryAddAjaxErrorModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
        {
            CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
        });
        return Json(categoryAddAjaxErrorModel);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int categoryId)
    {
        var result = await _categoryService.GetCategoryUpdateDtoAsync(categoryId);
        if (result.ResultStatus == ResultStatus.Success)
            return PartialView("_CategoryUpdatePartial", result.Data);
        else
            return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> Update(CategoryUpdateDto categoryUpdateDto)
    {
        if (ModelState.IsValid)
        {
            var result = await _categoryService.UpdateAsync(categoryUpdateDto, LoggedInUser.UserName);
            if (result.ResultStatus is ResultStatus.Success)
            {
                string categoryUpdateAjaxModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
                {
                    CategoryDto = result.Data,
                    CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)
                });
                return Json(categoryUpdateAjaxModel);
            }
        }
        string categoryUpdateAjaxErrorModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
        {
            CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)
        });
        return Json(categoryUpdateAjaxErrorModel);
    }

    public async Task<JsonResult> GetAllCategories()
    {
        var result = await _categoryService.GetAllByNonDeletedAsync();
        string categories = JsonSerializer.Serialize(result.Data, new JsonSerializerOptions
        {
            ReferenceHandler = ReferenceHandler.Preserve
        });
        return Json(categories);
    }

    [HttpPost]
    public async Task<JsonResult> Delete(int categoryId)
    {
        var result = await _categoryService.DeleteAsync(categoryId, LoggedInUser.UserName);
        string deletedCategory = JsonSerializer.Serialize(result.Data);
        return Json(deletedCategory);
    }
}

ProgrammersBlog.Mvc/Areas/Admin/ViewComponents/AdminMenuViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;

namespace ProgrammersBlog.Mvc.Areas.Admin.ViewComponents;

public class AdminMenuViewComponent : ViewComponent
{
    private readonly UserManager<User> _userManager;

    public AdminMenuViewComponent(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    public ViewViewComponentResult Invoke()
    {
        User user = _userManager.GetUserAsync(HttpContext.User).Result;
        IList<string> roles = _userManager.GetRolesAsync(user).Result;
        return View(new UserWithRolesViewModel
        {
            User = user,
            Roles = roles
        });
    }
}

ProgrammersBlog.Mvc/Areas/Admin/ViewComponents/UserMenuViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;

namespace ProgrammersBlog.Mvc.Areas.Admin.ViewComponents;

public class UserMenuViewComponent : ViewComponent
{
    private readonly UserManager<User> _userManager;

    public UserMenuViewComponent(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    public ViewViewComponentResult Invoke()
    {
        User user = _userManager.GetUserAsync(HttpContext.User).Result;
        return View(new UserViewModel
        {
            User = user
        }); 
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Admin Paneli | Programmers Blog</title>
    @await Html.PartialAsync("_LayoutCssPartial")
    @await RenderSectionAsync("Styles", false);
    <link href="~/AdminAreas/css/site.css" rel="stylesheet" />
</head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand ps-3" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Paneli</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Arama..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            @await Component.InvokeAsync("UserMenu")
        </nav>
        <div id="layoutSidenav">
            @await Component.InvokeAsync("AdminMenu")
            <div id="layoutSidenav_content">
                <main>
                <div class="container-fluid px-4">
                    @if(TempData["SuccessMessage"] is not null)
                    {
                        <div class="alert alert-success mt-2" role="alert">
                            @TempData["SuccessMessage"]
                        </div>
                    }
                    @RenderBody()
                </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Tüm Haklarını Sakladım &copy; Programmers Blog 2023</div>
                            <div>
                                <a href="#">Gizlilik Politikamız</a>
                                &middot;
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        @await Html.PartialAsync("_LayoutJsPartial")
        @await RenderSectionAsync("Scripts",false);
    </body>
</html>

ProgrammersBlog.Mvc/Areas/Admin/Views/Shared/_LayoutCssPartial.cshtml
<link href="~/AdminAreas/css/styles.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
<link href="https://cdn.datatables.net/buttons/1.6.3/css/buttons.bootstrap4.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

ProgrammersBlog.Mvc/Areas/Admin/Views/Shared/_LayoutJsPartial.cshtml
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/AdminAreas/js/scripts.js"></script>
<script src="~/AdminAreas/js/site.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script src="~/AdminAreas/assets/demo/chart-area-demo.js"></script>
<script src="~/AdminAreas/assets/demo/chart-bar-demo.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="~/AdminAreas/assets/demo/datatables-demo.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@@11"></script>
@await Component.InvokeAsync("NToastNotify")

ProgrammersBlog.Mvc/Areas/Admin/Views/Shared/_LayoutSideBarNavPartial.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Menü</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">İçerikler</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Categories" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
                    Kategoriler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Articles" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-file-alt"></i></div>
                    Makaleler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Comments" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-comments"></i></div>
                    Yorumlar
                </a>
                <div class="sb-sidenav-menu-heading">Kullanıcılar</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Roles" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-user-shield"></i></div>
                    Roller
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Users" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                    Kullanıcılar
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Giriş Yapan Kullanıcı:</div>
            Orçun Aşık
        </div>
    </nav>
</div>

ProgrammersBlog.Mvc/Areas/Admin/Views/Shared/_UserLoginLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title | ProgrammersBlog</title>
    <link href="~/AdminAreas/css/styles.css" rel="stylesheet" />
    <link href="~/AdminAreas/css/userLogin.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                @RenderBody()
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Tüm Haklarını Sakladım &copy; ProgrammersBlog 2024</div>
                        <div>
                            <a href="#">Gizlilik Politikası</a>
                            &middot;
                            <a href="#">Şartlar &amp; Koşullar</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js""></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminAreas/js/scripts.js"></script>
</body>
</html>